/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for the service.
         *
         *     Returns:
         *         HealthResponse with status "ok".
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in with email and password via Cognito.
         *
         *     Args:
         *         payload: Login request containing email and password.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Session tokens and user identity.
         *
         *     Raises:
         *         HTTPException: 400 if login fails; 503 if Cognito is not configured.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Sign up with email and optional username via Cognito.
         *
         *     Args:
         *         payload: Signup request containing email, password, and optional username.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Session tokens and user identity.
         *
         *     Raises:
         *         HTTPException: 400 if signup fails; 503 if Cognito is not configured.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Refresh an access token using a Cognito refresh token.
         *
         *     Args:
         *         payload: Refresh request.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         New session tokens.
         *
         *     Raises:
         *         HTTPException: 400 if refresh fails; 503 if Cognito is not configured.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Create a user profile (id and email).
         *
         *     Args:
         *         payload: User creation data containing id (UUID) and email.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Created user profile as UserRead schema.
         *
         *     Raises:
         *         HTTPException: 400 if user already exists.
         *
         *     Note:
         *         This endpoint is public. Signup already upserts a profile; this remains for clients that create one separately.
         */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get a user by UUID.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         User profile as UserRead schema.
         *
         *     Raises:
         *         HTTPException: 403 if trying to access another user's profile.
         *         HTTPException: 404 if user not found.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only access their own profile.
         */
        get: operations["get_user_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions For User
         * @description List game sessions for a user, newest first.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         List of game sessions as GameSessionRead schemas, ordered by created_at descending.
         *
         *     Raises:
         *         HTTPException: 403 if trying to access another user's sessions.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only list their own sessions.
         */
        get: operations["list_sessions_for_user_users__user_id__sessions_get"];
        put?: never;
        /**
         * Create Session For User
         * @description Create a game session for a user.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         payload: Game session creation data containing optional initial state.
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Created game session as GameSessionRead schema.
         *
         *     Raises:
         *         HTTPException: 403 if trying to create session for another user.
         *         HTTPException: 404 if user not found.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only create their own sessions.
         */
        post: operations["create_session_for_user_users__user_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthLoginRequest
         * @description Request body for POST /auth/login.
         *
         *     Attributes:
         *         email: User email address.
         *         password: User password.
         */
        AuthLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * AuthRefreshRequest
         * @description Request body for POST /auth/refresh.
         *
         *     Attributes:
         *         refresh_token: Cognito refresh token from a prior login/signup.
         *         username: Cognito username (email) required when the app client has a secret.
         */
        AuthRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
            /** Username */
            username?: string | null;
        };
        /**
         * AuthSessionResponse
         * @description Session payload returned by login, signup, and refresh.
         *
         *     Attributes:
         *         access_token: Cognito access token (send as Authorization: Bearer).
         *         refresh_token: Cognito refresh token.
         *         expires_in: Access token lifetime in seconds.
         *         token_type: Token type, always Bearer.
         *         user: Identity claims for the authenticated user.
         *         message: Optional note (e.g. email confirmation required).
         */
        AuthSessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Refresh Token
             * @default
             */
            refresh_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            user: components["schemas"]["AuthUser"];
            /** Message */
            message?: string | null;
        };
        /**
         * AuthSignupRequest
         * @description Request body for POST /auth/signup.
         *
         *     Attributes:
         *         email: User email address.
         *         password: User password.
         *         username: Optional display name stored on the Cognito user.
         */
        AuthSignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username?: string | null;
        };
        /**
         * AuthUser
         * @description Authenticated user identity returned with a session.
         *
         *     Attributes:
         *         id: Cognito user UUID (`sub`).
         *         email: User email if present on the token.
         *         username: Display name if present on the token.
         */
        AuthUser: {
            /** Id */
            id: string;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * GameSessionCreate
         * @description Payload to create a game session (optional initial state).
         *
         *     Attributes:
         *         state: Serialized Catan game state as dictionary (inherited from GameSessionBase).
         */
        GameSessionCreate: {
            /**
             * State
             * @description Serialized Catan game state.
             */
            state?: {
                [key: string]: unknown;
            };
        };
        /**
         * GameSessionRead
         * @description Game session as returned by the API (read-only fields).
         *
         *     Attributes:
         *         id: Game session ID (primary key).
         *         user_id: User UUID who owns the session.
         *         state: Serialized Catan game state as dictionary (inherited from GameSessionBase).
         *         created_at: Timestamp when the session was created.
         *         updated_at: Timestamp when the session was last updated.
         */
        GameSessionRead: {
            /**
             * State
             * @description Serialized Catan game state.
             */
            state?: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload for GET /health.
         *
         *     Attributes:
         *         status: Service status string.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * UserCreate
         * @description Payload to create a user profile linked to a Cognito user.
         *
         *     Attributes:
         *         id: Cognito user UUID (`sub`).
         *         email: User email address.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             * @description Cognito user UUID. Must match the authenticated `sub` claim.
             */
            id: string;
        };
        /**
         * UserRead
         * @description User as returned by the API (read-only fields).
         *
         *     Attributes:
         *         id: User UUID (primary key).
         *         email: User email address (inherited from UserBase).
         *         created_at: Timestamp when the user was created.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_for_user_users__user_id__sessions_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_for_user_users__user_id__sessions_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
