/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for the service.
         *
         *     Returns:
         *         HealthResponse with status "ok".
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in with email and password via Cognito.
         *
         *     Args:
         *         payload: Login request containing email and password.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Session tokens and user identity.
         *
         *     Raises:
         *         HTTPException: 400 if login fails; 429 when rate limited; 503 if Cognito is not configured.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Sign up with email and optional username via Cognito.
         *
         *     Args:
         *         payload: Signup request containing email, password, and optional username.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Whether email confirmation is pending, plus a session when it is not.
         *
         *     Raises:
         *         HTTPException: 400 if signup fails; 429 when rate limited; 503 if Cognito is not configured.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description Confirm a signup with the code Cognito emailed.
         *
         *     Args:
         *         payload: Email and confirmation code.
         *
         *     Returns:
         *         Acknowledgement; log in afterwards.
         *
         *     Raises:
         *         HTTPException: 400 if the code is wrong or expired; 429 when rate limited.
         */
        post: operations["confirm_auth_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Confirmation
         * @description Email a fresh confirmation code.
         *
         *     Args:
         *         payload: Email used at signup.
         *
         *     Returns:
         *         Acknowledgement, identical whether or not the account exists.
         *
         *     Raises:
         *         HTTPException: 400 on a Cognito error; 429 when rate limited.
         */
        post: operations["resend_confirmation_auth_resend_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Refresh an access token using a Cognito refresh token.
         *
         *     Args:
         *         payload: Refresh request.
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         New session tokens.
         *
         *     Raises:
         *         HTTPException: 400 if refresh fails; 429 when rate limited; 503 if Cognito is not configured.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the refresh token and sign out the current session.
         *
         *     the bearer token is optional and not validated: an expired access token
         *     must still be able to log out.
         *
         *     Args:
         *         payload: Refresh token to revoke.
         *         authorization: Optional "Bearer <token>" header.
         *
         *     Returns:
         *         Acknowledgement.
         *
         *     Raises:
         *         HTTPException: 429 when rate limited; 503 if Cognito is not configured.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get a user by UUID.
         *
         *     profiles are created by signup and login; there is no public create route.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         User profile as UserRead schema.
         *
         *     Raises:
         *         HTTPException: 403 if trying to access another user's profile.
         *         HTTPException: 404 if user not found.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only access their own profile.
         */
        get: operations["get_user_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions For User
         * @description List game sessions for a user, newest first.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         List of game sessions as GameSessionRead schemas, ordered by created_at descending.
         *
         *     Raises:
         *         HTTPException: 403 if trying to access another user's sessions.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only list their own sessions.
         */
        get: operations["list_sessions_for_user_users__user_id__sessions_get"];
        put?: never;
        /**
         * Create Session For User
         * @description Create a game session for a user.
         *
         *     Args:
         *         user_id: User UUID as string (from path parameter).
         *         payload: Game session creation data containing optional initial state.
         *         current_user: Authenticated user (injected dependency).
         *         db: Database session (injected dependency).
         *
         *     Returns:
         *         Created game session as GameSessionRead schema.
         *
         *     Raises:
         *         HTTPException: 403 if trying to create session for another user.
         *         HTTPException: 404 if user not found.
         *
         *     Note:
         *         Requires Authorization header with a valid Cognito access token.
         *         Users can only create their own sessions.
         */
        post: operations["create_session_for_user_users__user_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthConfirmRequest
         * @description Request body for POST /auth/confirm.
         *
         *     Attributes:
         *         email: Email used at signup.
         *         code: Verification code Cognito emailed to that address.
         */
        AuthConfirmRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
        };
        /**
         * AuthLoginRequest
         * @description Request body for POST /auth/login.
         *
         *     Attributes:
         *         email: User email address.
         *         password: User password.
         */
        AuthLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * AuthLogoutRequest
         * @description Request body for POST /auth/logout.
         *
         *     Attributes:
         *         refresh_token: Refresh token to revoke. its access tokens stop working too.
         */
        AuthLogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * AuthMessageResponse
         * @description Acknowledgement for auth actions that return no session.
         *
         *     Attributes:
         *         message: Human-readable outcome.
         */
        AuthMessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * AuthRefreshRequest
         * @description Request body for POST /auth/refresh.
         *
         *     Attributes:
         *         refresh_token: Cognito refresh token from a prior login/signup.
         *         username: Cognito username (email) required when the app client has a secret.
         */
        AuthRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
            /** Username */
            username?: string | null;
        };
        /**
         * AuthResendConfirmationRequest
         * @description Request body for POST /auth/resend-confirmation.
         *
         *     Attributes:
         *         email: Email used at signup.
         */
        AuthResendConfirmationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * AuthSessionResponse
         * @description Session payload returned by login, signup, and refresh.
         *
         *     Attributes:
         *         access_token: Cognito access token (send as Authorization: Bearer).
         *         refresh_token: Cognito refresh token.
         *         expires_in: Access token lifetime in seconds.
         *         token_type: Token type, always Bearer.
         *         user: Identity claims for the authenticated user.
         *         message: Optional note (e.g. email confirmation required).
         */
        AuthSessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Refresh Token
             * @default
             */
            refresh_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            user: components["schemas"]["AuthUser"];
            /** Message */
            message?: string | null;
        };
        /**
         * AuthSignupRequest
         * @description Request body for POST /auth/signup.
         *
         *     Attributes:
         *         email: User email address.
         *         password: User password.
         *         username: Optional display name stored on the Cognito user.
         */
        AuthSignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username?: string | null;
        };
        /**
         * AuthSignupResponse
         * @description Payload returned by signup.
         *
         *     Attributes:
         *         email: Address the account was created for.
         *         confirmation_required: True when Cognito emailed a verification code and
         *             the client must call /auth/confirm before logging in.
         *         session: Session tokens, only when the account was confirmed at once
         *             (local development against the emulator).
         */
        AuthSignupResponse: {
            /** Email */
            email: string;
            /** Confirmation Required */
            confirmation_required: boolean;
            session?: components["schemas"]["AuthSessionResponse"] | null;
        };
        /**
         * AuthUser
         * @description Authenticated user identity returned with a session.
         *
         *     Attributes:
         *         id: Cognito user UUID (`sub`).
         *         email: User email if present on the token.
         *         username: Display name if present on the token.
         */
        AuthUser: {
            /** Id */
            id: string;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * GameSessionCreate
         * @description Payload to create a game session (optional initial state).
         *
         *     Attributes:
         *         state: Serialized Catan game state as dictionary (inherited from GameSessionBase).
         */
        GameSessionCreate: {
            /**
             * State
             * @description Serialized Catan game state.
             */
            state?: {
                [key: string]: unknown;
            };
        };
        /**
         * GameSessionRead
         * @description Game session as returned by the API (read-only fields).
         *
         *     Attributes:
         *         id: Game session ID (primary key).
         *         user_id: User UUID who owns the session.
         *         state: Serialized Catan game state as dictionary (inherited from GameSessionBase).
         *         created_at: Timestamp when the session was created.
         *         updated_at: Timestamp when the session was last updated.
         */
        GameSessionRead: {
            /**
             * State
             * @description Serialized Catan game state.
             */
            state?: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload for GET /health.
         *
         *     Attributes:
         *         status: Service status string.
         */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * UserRead
         * @description User as returned by the API (read-only fields).
         *
         *     Attributes:
         *         id: User UUID (primary key).
         *         email: User email address (inherited from UserBase).
         *         created_at: Timestamp when the user was created.
         */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_auth_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_confirmation_auth_resend_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthResendConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_for_user_users__user_id__sessions_get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_for_user_users__user_id__sessions_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
