"""mkdocs hooks: copy the committed OpenAPI schema into the docs tree.

the schema is generated by `mise run api` into frontend/src/api/openapi.json;
this hook copies it next to api.md at build time so the redoc page can load it.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SOURCE = _REPO_ROOT / 'frontend' / 'src' / 'api' / 'openapi.json'
_TARGET = _REPO_ROOT / 'docs' / 'openapi.json'


def on_pre_build(config: Any, **kwargs: Any) -> None:
    """copy the openapi schema into docs/ before mkdocs collects files.

    Args:
        config: the mkdocs config object (unused).
        **kwargs: extra hook arguments (unused).

    Raises:
        FileNotFoundError: if the schema has not been generated yet.
    """
    if not _SOURCE.exists():
        raise FileNotFoundError(f'{_SOURCE} is missing; run `mise run api` first')
    shutil.copyfile(_SOURCE, _TARGET)
